// Code generated by protoc-gen-go.
// source: data/item.proto
// DO NOT EDIT!

/*
Package data is a generated protocol buffer package.

It is generated from these files:
	data/item.proto
	data/user.proto

It has these top-level messages:
	Item
	User
*/
package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Item struct {
	Label string `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Type  int32  `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Reps  int64  `protobuf:"varint,3,opt,name=reps" json:"reps,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Item)(nil), "data.Item")
}

func init() { proto.RegisterFile("data/item.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x49, 0x2c, 0x49,
	0xd4, 0xcf, 0x2c, 0x49, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x09, 0x28,
	0xb9, 0x70, 0xb1, 0x78, 0x96, 0xa4, 0xe6, 0x0a, 0x89, 0x70, 0xb1, 0xe6, 0x24, 0x26, 0xa5, 0xe6,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0x42, 0x5c, 0x2c, 0x25, 0x95, 0x05,
	0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x60, 0x36, 0x48, 0xac, 0x28, 0xb5, 0xa0, 0x58,
	0x82, 0x59, 0x81, 0x51, 0x83, 0x39, 0x08, 0xcc, 0x4e, 0x62, 0x03, 0x1b, 0x69, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x18, 0x0a, 0x6e, 0x38, 0x65, 0x00, 0x00, 0x00,
}
